excluded:
  - Pods
  - UnitTests
  - DerivedData
  - PresentationLayer/Resources
  
allow_zero_lintable_files: true

analyzer_rules:
  - unused_import

disabled_rules: # rule identifiers to exclude from running
  - opening_brace
  - statement_position
  - vertical_parameter_alignment
  - legacy_constructor
  - identifier_name
  - legacy_cggeometry_functions
  - legacy_constant
  - trailing_newline
  - empty_count
  - force_cast
  - type_name
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
  - function_parameter_count
  - force_try
  - control_statement
  - trailing_whitespace
  - leading_whitespace
  - operator_whitespace
  - file_length
  - mark
  - weak_delegate
  - discarded_notification_center_observer
  - colon
  - force_unwrapping

opt_in_rules: # some rules are only opt-in
  - overridden_super_call
  - prohibited_super_call
  - empty_count
  - explicit_init
  - force_unwrapping
  - operator_usage_whitespace
  - anyobject_protocol
  - array_init
  - block_based_kvo
#  - closure_body_length
  - closure_spacing
  - vertical_whitespace_closing_braces
  - vertical_parameter_alignment_on_call
  - collection_alignment

large_tuple: 4

line_length:
  warning: 300
  error: 350

function_parameter_count:
  warning: 10
  error: 15

file_length:
  warning: 500

type_body_length:
  warning: 400
  error: 450

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length: 1
  max_length: 65

type_name:
  min_length: 3
  max_length: 65

custom_rules:
  vertical_whitespace_before_mark:
    regex: '[A-Za-z0-9а-яА-ЯёЁ\/]\n([ \t]*)\/\/[\s*]MARK'
    name: "Vertical Whitespace before MARK"
    message: "Include vertical whitespace (empty line) before MARK."

  vertical_whitespace_after_mark:
    included: ".*\\.swift"
    regex: '\/\/[\s*]MARK[^\n\r]*\n[ \t]*?[A-Za-z0-9а-яА-ЯёЁ\/]'
    name: "Vertical Whitespace after MARK"
    message: "Include vertical whitespace (empty line) after MARK."
    severity: warning

  wrong_mark_syntax:
    included: ".*\\.swift"
    regex: '\/\/[\s*]MARK:([^ ]|\s[^\-]| \-[^ ])'
    name: "Wrong MARK syntax"
    message: "Use MARK: - syntax"
    severity: warning

  wrong_todo_syntax:
    included: ".*\\.swift"
    regex: '\/\/[\s*]TODO:([^ ]| [^\(0-9)]| [0-9]\.[^(0-9)])'
    name: "Wrong TODO syntax"
    message: "Use TODO: 4.9 syntax"
    severity: warning

  wrong_letter:
    included: ".*\\.swift"
    regex: '[а-яА-Я][a-zA-Z]'
    name: "Wrong russian or english letter"
    message: "Replace latter to correct"
    severity: warning

  insecure_url_usage:
    included: ".*\\.swift"
    regex: '(http):\/\/(www\.)?+[^\s\/\$.?#]+.[\S]+[$\s]'
    name: "Insecure url usage"
    match_kinds:
        - argument
        - buildconfig.id
        - buildconfig.keyword
        - identifier
        - keyword
        - objectliteral
        - parameter
        - placeholder
        - string
        - string_interpolation_anchor
    message: "Don't use http for urls. Replace with https"
    severity: warning

  testable_import:
    included: ".*\\.swift"
    # Исключая файлы содержащие в пути директории Tests или Mocks или заканчивающиеся на 'Test(s).swift', 'Mock.swift', 'Stub.swift'
    excluded: "(\\/Tests\\/.+|\\/Mocks\\/.*|Tests*|Mock|Stub)\\.swift$"
    name: "@testable import"
    regex: "@testable import"
    message: "Use testable imports only in test classes"
    severity: error
